import { describe, expect, it } from "vitest"

import artifacts from "./fixtures/artifacts.json"
import chunkMarkdown from "./fixtures/chunk_set.markdown_header.json"
import chunkRecursive from "./fixtures/chunk_set.recursive_character.json"
import chunkToken from "./fixtures/chunk_set.token_based.json"
import parsedDoc from "./fixtures/parsed_doc.json"
import cleanedDoc from "./fixtures/parsed_doc_cleaned.json"
import registry from "./fixtures/registry.json"
import type { Chunk, ChunkSet, Element, ParsedDoc, TransformInfo } from "./types"

// Runtime key checks: the fixtures are generated by the engine, so a field the
// engine adds or renames shows up here as a failing test, not as `undefined`
// deep in an inspector.
const keys = (o: object) => Object.keys(o).sort()

const TRANSFORM_KEYS: (keyof TransformInfo)[] = [
  "cacheable", "config_schema", "deterministic", "inputs", "name", "output",
  "provides", "requires", "stackable", "stage", "version",
]
const ELEMENT_KEYS: (keyof Element)[] = [
  "bbox", "id", "level", "md_end", "md_start", "order", "page", "parent_id", "text", "type",
]
const DOC_KEYS: (keyof ParsedDoc)[] = [
  "doc_meta", "elements", "filename", "page_count", "parser_meta", "source_id",
]
const CHUNK_KEYS: (keyof Chunk)[] = [
  "doc_id", "embed_text", "end_char", "heading_path", "id", "kind", "level", "metadata",
  "ordinal", "page_span", "parent_id", "source_element_ids", "start_char", "text", "token_count",
]
const CHUNK_SET_KEYS: (keyof ChunkSet)[] = [
  "chunker_meta", "chunks", "doc_id", "source_text",
]

describe("types mirror the engine's real payloads", () => {
  it("registry entries carry exactly the TransformInfo fields", () => {
    const entries = Object.values(registry).flatMap((stage) => Object.values(stage))
    expect(entries.length).toBeGreaterThanOrEqual(14)
    for (const t of entries) {
      // `summary` (plan I-11) is additive: fixtures exported before it lack it.
      expect(keys(t).filter((k) => k !== "summary")).toEqual([...TRANSFORM_KEYS].sort())
      if ("summary" in t) expect(typeof t.summary === "string" && t.summary.length > 0).toBe(true)
    }
  })

  it.each([
    ["parsed", parsedDoc],
    ["cleaned", cleanedDoc],
  ])("%s ParsedDoc and its elements", (_, doc) => {
    expect(keys(doc)).toEqual([...DOC_KEYS].sort())
    for (const el of doc.elements) expect(keys(el)).toEqual([...ELEMENT_KEYS].sort())
  })

  it("the cleaned doc carries one clean_report entry per cleaner, in order", () => {
    const report = cleanedDoc.parser_meta.clean_report
    expect(report.map((r) => r.cleaner)).toEqual(["header_footer_strip", "dedupe_blocks"])
    expect(report[0].removed_count).toBeGreaterThan(0)
  })

  it.each([
    ["recursive_character", chunkRecursive],
    ["markdown_header", chunkMarkdown],
    ["token_based", chunkToken],
  ])("%s ChunkSet slices back to its source text", (_, set) => {
    expect(keys(set)).toEqual([...CHUNK_SET_KEYS].sort())
    for (const c of set.chunks) {
      expect(keys(c)).toEqual([...CHUNK_KEYS].sort())
      expect(set.source_text.slice(c.start_char, c.end_char)).toBe(c.text)
    }
  })

  it("the three chunkers really do cut the document differently", () => {
    const cuts = [chunkRecursive, chunkMarkdown, chunkToken].map((s) =>
      s.chunks.map((c) => `${c.start_char}-${c.end_char}`).join(","),
    )
    expect(new Set(cuts).size).toBe(3)
    expect(Object.keys(artifacts)).toContain("chunk_token")
  })
})
